"""empty message

Revision ID: 22d728140822
Revises: ecc27c395564
Create Date: 2022-07-05 16:48:02.519069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d728140822'
down_revision = 'ecc27c395564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('date_collected', sa.DateTime(), nullable=True, comment='DMY sample was collected'))
    op.add_column('sample', sa.Column('date_received', sa.DateTime(), nullable=True, comment='DMY the sample was received'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'date_received')
    op.drop_column('sample', 'date_collected')
    # ### end Alembic commands ###
