"""empty message

Revision ID: 6e7ec8818826
Revises: 7a150ee4568a
Create Date: 2023-01-10 14:57:11.719492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7ec8818826'
down_revision = '7a150ee4568a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bactopia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.VARCHAR(length=60), nullable=True, comment='The name of bactopia process'),
    sa.Column('results', sa.VARCHAR(length=60), nullable=True, comment='The storage path of results for a bactopia process'),
    sa.Column('notes', sa.VARCHAR(length=60), nullable=True, comment='AOB regarding the bactopia process'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bactopia')
    # ### end Alembic commands ###
