"""empty message

Revision ID: 7a150ee4568a
Revises: 9f72c83a95f5
Create Date: 2023-01-10 14:42:29.725414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a150ee4568a'
down_revision = '9f72c83a95f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assembly', sa.Column('notes', sa.VARCHAR(length=250), nullable=True, comment='AOB regarding the assembly process'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assembly', 'notes')
    # ### end Alembic commands ###
