"""empty message

Revision ID: 84a3c58d3a80
Revises: ecc27c395564
Create Date: 2022-07-04 09:08:56.391209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84a3c58d3a80'
down_revision = 'ecc27c395564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'date_received')
    op.drop_column('sample', 'date_collected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('date_collected', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='DMY sample was collected'))
    op.add_column('sample', sa.Column('date_received', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='DMY the sample was received'))
    # ### end Alembic commands ###
